// FIND ALL
GET http://localhost:4000/api/users
###

// REGISTER
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
    "username": "Victor",
    "password": "66733",
    "role": "bhagwan"
}
###

// FIND BY ID
GET http://localhost:4000/api/users/608147d0e8f73c225477a932
###
///

// FIND BY ID AND DELETE
DELETE http://localhost:4000/api/users/6081476fcd4a70223a89fb66
###
///

// FIND BY ID AND UPDATE
PUT http://localhost:4000/api/users/608147d0e8f73c225477a932
Content-Type: application/json

{
    "username": "Oscar",
    "password": "36043",
    "role": "Soldier"
}
###

// AUTHENTICATE LOGIN
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "username": "Victor",
    "password": "66733"
}