
// FIND ALL
GET http://localhost:4000/api/frames

###

// CREATE NEW 
POST http://localhost:4000/api/frames
Content-Type: application/json

{
    "title": "Hermans inlägg nr 4",
    "description": "blablabkla",
    "author": "Herman",
    "image": "https://images.unsplash.com/photo-1599447332712-112c3d0cefb4",
    "date": "2020-01-09"
}

###

// FIND ONE BY ID
GET http://localhost:4000/api/frames/60813bd9d226bb1817eb6b74

###

// FIND BY ID AND UPDATE
PUT http://localhost:4000/api/frames/60813e3ca84ba21ff0664b19
Content-Type: application/json

{
    "title": "Herman",
    "description": "757687868",
    "author": "SWEDEN"
}

###

// FIND BY ID AND DELETE
DELETE http://localhost:4000/api/frames/6087bc2723abf67562a27c77