
// FIND ALL
GET http://localhost:4000/api/posts

###

// CREATE NEW 
POST http://localhost:4000/api/posts
Content-Type: application/json

{
    "title": "Hermans inlägg",
    "description": "blablabkla",
    "author": "Herman"
}

###

// FIND ONE BY ID
GET http://localhost:4000/api/posts/60813bd9d226bb1817eb6b74

###

// FIND BY ID AND UPDATE
PUT http://localhost:4000/api/posts/608133b61b75db0aaf7ae5f4
Content-Type: application/json

{
    "title": "Herman",
    "description": "757687868",
    "author": "SWEDEN"
}

###

// FIND BY ID AND DELETE
DELETE http://localhost:4000/api/posts/608133b21b75db0aaf7ae5f3